# Generated by Django 5.0.4 on 2024-06-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='address',
            new_name='city',
        ),
    ]
