# Generated by Django 5.0.4 on 2024-04-28 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0004_rename_superuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bloodType', models.CharField(max_length=3)),
                ('emergencyContact', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=200)),
                ('noOfDonations', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('authUser.user',),
        ),
    ]
