# Generated by Django 5.0.4 on 2024-07-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0005_remove_donor_noofdonations_alter_person_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='diseases',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
