# Generated by Django 5.0.4 on 2024-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0006_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
