# Generated by Django 5.0.4 on 2024-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='disease',
            new_name='diseases',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='disease',
            new_name='diseases',
        ),
        migrations.AddField(
            model_name='donor',
            name='allergies',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
