# Generated by Django 5.0.4 on 2024-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0008_donation_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_record',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
