# Generated by Django 5.0.4 on 2024-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0009_rename_disease_donor_diseases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='diseases',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diseases',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
