# Generated by Django 5.0.4 on 2024-07-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0009_alter_donation_record_amount_alter_patient_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
