# Generated by Django 5.0.4 on 2024-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0010_alter_donor_diseases_alter_patient_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
