# Generated by Django 5.0.4 on 2024-06-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0012_alter_donor_bloodtype_alter_patient_bloodtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='allergies',
        ),
    ]
