# Generated by Django 5.0.4 on 2024-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0013_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=100),
        ),
    ]
