# Generated by Django 5.0.4 on 2024-07-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0014_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='dedicatedBloodBag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dedicated_BloodBags', to='authUser.blood_bag'),
        ),
    ]
