# Generated by Django 5.0.4 on 2024-07-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authUser', '0016_remove_notification_recipients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipients',
            new_name='recipient',
        ),
    ]
